# Generated by Django 4.2.7 on 2025-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="html_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notificationcategory",
            name="default_email_template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("order_placed_email.html", "Order Placed"),
                    ("order_shipped_email.html", "Order Shipped"),
                    ("order_delivered_email.html", "Order Delivered"),
                    ("security_alert_email.html", "Security Alert"),
                    ("marketing_email.html", "Marketing"),
                    ("base_email_template.html", "Generic Email"),
                ],
                default="base_email_template.html",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="notificationcategory",
            name="primary_color",
            field=models.CharField(blank=True, default="#4CAF50", max_length=20),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="company_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="html_template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("order_placed_email.html", "Order Placed"),
                    ("order_shipped_email.html", "Order Shipped"),
                    ("order_delivered_email.html", "Order Delivered"),
                    ("security_alert_email.html", "Security Alert"),
                    ("marketing_email.html", "Marketing"),
                    ("base_email_template.html", "Generic Email"),
                ],
                help_text="HTML template file to use for email",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="logo_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="primary_color",
            field=models.CharField(blank=True, default="#4CAF50", max_length=20),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="use_html_template",
            field=models.BooleanField(default=True),
        ),
    ]
